package dev.vibeafrika.pcm.infrastructure.encryption;

import dev.vibeafrika.pcm.domain.encryption.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;

import java.util.Map;
import java.util.UUID;

/**
 * Scheduled service that enforces secret rotation policies for all secret types.
 *
 * <p>Rotation schedules:
 * <ul>
 *   <li>API tokens: every 90 days</li>
 *   <li>Database credentials: quarterly (every 90 days)</li>
 *   <li>Service secrets: quarterly (every 90 days)</li>
 * </ul>
 *
 * <p>All rotation events are audit-logged via {@link IAuditLogger}.
 *
 * <p>This scheduler checks for overdue secrets every hour and delegates rotation
 * to {@link SecretManager#rotateSecret}. In production, the new secret value would
 * be generated by the owning service and supplied via an out-of-band mechanism;
 * here the scheduler signals that rotation is due and logs the event.
 */
public class SecretRotationScheduler {

    private static final Logger logger = LoggerFactory.getLogger(SecretRotationScheduler.class);

    private final SecretManager secretManager;
    private final IAuditLogger auditLogger;

    public SecretRotationScheduler(SecretManager secretManager, IAuditLogger auditLogger) {
        this.secretManager = secretManager;
        this.auditLogger = auditLogger;
    }

    /**
     * Runs every hour to detect secrets that are overdue for rotation.
     *
     * <p>For each overdue secret, a CRITICAL-level security event is logged so that
     * the owning service can supply a new value and call
     * {@link ISecretManager#rotateSecret}.
     */
    @Scheduled(fixedDelayString = "PT1H")
    public void checkAndRotateOverdueSecrets() {
        logger.debug("Running scheduled secret rotation check");

        for (Map.Entry<UUID, SecretManager.SecretRecord> entry :
                secretManager.secretStore.entrySet()) {

            UUID secretId = entry.getKey();
            SecretManager.SecretRecord record = entry.getValue();

            if (record.status != KeyStatus.ACTIVE) {
                continue;
            }

            if (secretManager.isDueForRotation(secretId)) {
                logger.warn("Secret overdue for rotation: id={}, name={}, type={}, context={}",
                    secretId, record.secretName, record.secretType, record.context);

                logRotationDueEvent(secretId, record);
            }
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Private helpers
    // ─────────────────────────────────────────────────────────────────────────

    private void logRotationDueEvent(UUID secretId, SecretManager.SecretRecord record) {
        try {
            SecurityEvent event = SecurityEvent.builder()
                .timestamp(java.time.Instant.now())
                .context(record.context)
                .serviceIdentity("SecretRotationScheduler")
                .eventType("SECRET_ROTATION_DUE")
                .severity(LogLevel.CRITICAL.name())
                .keyId(secretId)
                .description("Secret '" + record.secretName + "' of type " + record.secretType
                    + " is overdue for rotation (schedule: every "
                    + SecretManager.ROTATION_INTERVAL_DAYS + " days)")
                .build();
            auditLogger.logSecurityEvent(event);
        } catch (Exception e) {
            logger.warn("Failed to log rotation-due event for secretId={}: {}", secretId, e.getMessage());
        }
    }
}
